projects:
  mikro:
    schema: http://localhost:8080/graphql
    documents: graphql/**.graphql
    extensions:
      turms:
        out_dir: examples/api
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
            query_bases:
              - "rath.turms.operation.GraphQLQuery"
            mutation_bases:
              - "rath.turms.operation.GraphQLMutation"
            subscription_bases:
              - "rath.turms.operation.GraphQLSubscription"
          - type: turms.plugins.funcs.OperationsFuncPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          XArray: str
          File: str
          ImageFile: str
          Upload: str
          DataFrame: str
          Store: str
