projects:
  default:
    schema: https://api.spacex.land/graphql/
    documents: graphql/**.graphql
    extensions:
      turms:
        out_dir: examples/api
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
            query_bases:
              - "rath.turms.operation.GraphQLQuery"
            mutation_bases:
              - "rath.turms.operation.GraphQLMutation"
            subscription_bases:
              - "rath.turms.operation.GraphQLSubscription"
          - type: turms.plugins.funcs.OperationsFuncPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          uuid: str
