projects:
  default:
    schema: tests/schema.graphql
    documents: graphql/test/**.graphql
    extensions:
      turms:
        out_dir: tests/apis
        generated_name: tests.py
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
          - type: rath.turms.plugins.funcs.RathFuncsPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          uuid: str
  countries:
    schema: https://countries.trevorblades.com/
    documents: graphql/countries/**.graphql
    extensions:
      turms:
        out_dir: tests/apis/
        generated_name: countries.py
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operation.OperationsPlugin
          - type: rath.turms.plugins.funcs.RathFuncsPlugin
        processors:
          - type: turms.processor.black.BlackProcessor
        scalar_definitions:
          uuid: str
